### PR TITLE
updated IronOS.gif

### PR DESCRIPTION
**Pull request by discip**

### CODE REVIEW

**Comment by discip** [comment]
@Ralim
Could you please update the files on the release page once more? 😊

Thanks!

**Comment by discip** [comment]
@Ralim
Could you please update the files on the release page once more? 😊

Thanks!

**Comment by discip** [comment]
# Thank you! 👍

**Comment by Ralim** [comment]
Done & automated so I shouldn't forget now.

**Comment by Ralim** [comment]
Far easier to automate it once so you don't have to nag me 🙃

**Comment by discip** [comment]
@Ralim
Sorry to nag one more time.
But after the automation the files are nested inside 2 more folders **`tmp/miniware/...`**.
Could you please fix that as well?

Thanks in advance

**Pull request merged**
