### PR TITLE
Print size of frames

### PR DESCRIPTION
**Pull request by Ralim**

### CODE REVIEW

**Comment by discip** [comment]
@Ralim
Sorry for nagging, but now there is on minor issue regarding the enumeration of the frames.
Now it starts at ***frame 0*** instead of ***frame 1***.

Could you please change that to ***frame 1*** again?

thanks in advance

**Comment by Ralim** [comment]
It always did, I just forgot to print frame 0 😅

**Comment by discip** [comment]
But *frame 0* is somewhat surreal! 😁
## So the -1 should be reverted I guess!

**Comment by Ralim** [comment]
I agree, guess it's my inner programmer to count from 0 😮

I'll update to fix the counting to be friendly with frame 1,2,3 and so on

**Comment by discip** [comment]
@Ralim
> I'll update to fix the counting to be friendly with frame 1,2,3 and so on

Already created a PR addressing that one.

One more thing:
The *sum* being *calculated* ***adds 2 extra bytes*** compared to summing up the individual sizes by *hand*.
Do the individual sizes get *rounded up?*
Could you please have a look on that?

**Pull request merged**
